// <auto-generated />
namespace BusinessERP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class BusinessERP_20_V1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BusinessERP_20_V1));
        
        string IMigrationMetadata.Id
        {
            get { return "202104251546417_BusinessERP_2.0_V1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
